include:
  - docker-compose-ode.yml

services:
  conflictmonitor-build:
    profiles:
      - all
      - cm_full
      - cm_base
      - cm_build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAVEN_GITHUB_TOKEN: ${MAVEN_GITHUB_TOKEN:?error}
        MAVEN_GITHUB_ORG: ${MAVEN_GITHUB_ORG:?error}
    image: jpo-conflictmonitor:latest
    restart: ${RESTART_POLICY}
    ports:
      - "8082:8082"
      - "10090:10090" # JMX
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP:?error}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:?error}
      CONNECT_URL: ${CONNECT_URL:?error}
      spring.kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:?error}
    healthcheck:
      test: ["CMD", "java", "-version"]
      interval: 10s
      timeout: 10s
      retries: 20
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 3G
    depends_on:
      kafka:
        condition: service_healthy
        required: false

  conflictmonitor-release:
    profiles:
      - cm_release
    image: usdotjpoode/jpo-conflictmonitor:latest
    restart: ${RESTART_POLICY}
    ports:
      - "8082:8082"
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP:?error}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:?error}
      CONNECT_URL: ${CONNECT_URL:?error}
      spring.kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:?error}
    healthcheck:
      test: ["CMD", "java", "-version"]
      interval: 10s
      timeout: 10s
      retries: 20
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 3G
    depends_on:
      kafka:
        condition: service_healthy
        required: false

#  deduplicator:
#    profiles:
#      - all
#      - cm_full
#      - cm_base
#      - deduplicator
#    build:
#      context: .
#      dockerfile: Dedup_Dockerfile
#      args:
#        MAVEN_GITHUB_TOKEN: ${MAVEN_GITHUB_TOKEN:?error}
#        MAVEN_GITHUB_ORG: ${MAVEN_GITHUB_ORG:?error}
#    image: jpo-deduplicator:latest
#    restart: ${RESTART_POLICY}
#    environment:
#      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
#      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:?error}
#      spring.kafka.bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:?error}
#    healthcheck:
#      test: ["CMD", "java", "-version"]
#      interval: 10s
#      timeout: 10s
#      retries: 20
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "5"
#    deploy:
#      resources:
#        limits:
#          memory: 3G
#    depends_on:
#      kafka:
#        condition: service_healthy
#        required: false
