version: '3.9'
services:
  conflictmonitor:
    build: .
    image: jpo-conflictmonitor:latest
    restart: always
    ports:
      - "8082:8082"
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}
      KAFKA_BROKER_IP: ${KAFKA_BROKER_IP}
      DB_HOST_IP: ${DB_HOST_IP}
      spring.kafka.bootstrap-servers: ${KAFKA_BROKER_IP}:9092
      spring.data.mongodb.uri: mongodb://${DB_HOST_IP}:27017
    logging:
      options:
        max-size: "10m"
        max-file: "5"
